#**3. Descriptive Statistics - Measures of Central Tendency & Variability**#

In [1]:
import pandas as pd

##**Dataset - 1: nba.csv**##

In [2]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Datasets/nba.csv")

In [3]:
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [4]:
df.shape

(458, 9)

In [28]:
mode = df['College'].mode()[0]
df['College'].fillna(mode,inplace=True)

In [5]:
df.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [6]:
df.fillna("No Data", inplace=True)

###**Summary Statistics of Income Grouped by Age Groups**###

In [7]:
df['Salary'].value_counts()

947276.0     31
845059.0     18
525093.0     13
No Data      12
981348.0      6
             ..
2100000.0     1
1252440.0     1
2891760.0     1
3272091.0     1
900000.0      1
Name: Salary, Length: 310, dtype: int64

In [8]:
df['Height'].value_counts()

6-9        59
6-10       47
6-7        45
6-8        43
6-6        42
6-11       40
6-3        33
6-5        32
6-4        29
7-0        27
6-1        16
6-2        16
6-0        10
7-1         7
7-3         4
5-11        3
7-2         3
5-9         1
No Data     1
Name: Height, dtype: int64

In [9]:
height_groups = df.groupby(df['Height'])

In [10]:
height_groups.get_group('6-11')

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
55,Nerlens Noel,Philadelphia 76ers,4.0,PF,22.0,6-11,228.0,Kentucky,3457800.0
56,Jahlil Okafor,Philadelphia 76ers,8.0,C,20.0,6-11,275.0,Duke,4582680.0
60,Christian Wood,Philadelphia 76ers,35.0,PF,20.0,6-11,220.0,UNLV,525093.0
73,Jason Thompson,Toronto Raptors,1.0,PF,29.0,6-11,250.0,Rider,245177.0
81,Festus Ezeli,Golden State Warriors,31.0,C,26.0,6-11,265.0,Vanderbilt,2008748.0
90,Anderson Varejao,Golden State Warriors,18.0,PF,33.0,6-11,273.0,No Data,289755.0
91,Cole Aldrich,Los Angeles Clippers,45.0,C,27.0,6-11,250.0,Kansas,1100602.0
98,DeAndre Jordan,Los Angeles Clippers,6.0,C,27.0,6-11,265.0,Texas A&M,19689000.0
113,Ryan Kelly,Los Angeles Lakers,4.0,PF,25.0,6-11,230.0,Duke,1724250.0
143,DeMarcus Cousins,Sacramento Kings,15.0,C,25.0,6-11,270.0,Kentucky,15851950.0
162,Joakim Noah,Chicago Bulls,13.0,C,31.0,6-11,232.0,Florida,13400000.0
163,Bobby Portis,Chicago Bulls,5.0,PF,21.0,6-11,230.0,Arkansas,1391160.0
167,Channing Frye,Cleveland Cavaliers,9.0,PF,33.0,6-11,255.0,Arizona,8193029.0
173,Sasha Kaun,Cleveland Cavaliers,14.0,C,31.0,6-11,260.0,Kansas,1276000.0
188,Andre Drummond,Detroit Pistons,0.0,C,22.0,6-11,279.0,Connecticut,3272091.0
204,Ian Mahinmi,Indiana Pacers,28.0,C,29.0,6-11,250.0,No Data,4000000.0
208,Myles Turner,Indiana Pacers,33.0,PF,20.0,6-11,243.0,Texas,2357760.0
209,Shayne Whittington,Indiana Pacers,42.0,PF,25.0,6-11,250.0,Western Michigan,845059.0
211,Giannis Antetokounmpo,Milwaukee Bucks,34.0,SF,21.0,6-11,222.0,No Data,1953960.0
216,John Henson,Milwaukee Bucks,31.0,PF,25.0,6-11,229.0,North Carolina,2943221.0
220,Greg Monroe,Milwaukee Bucks,15.0,C,26.0,6-11,265.0,Georgetown,16407500.0
224,Miles Plumlee,Milwaukee Bucks,18.0,C,27.0,6-11,249.0,Duke,2109294.0
237,Zaza Pachulia,Dallas Mavericks,27.0,C,32.0,6-11,275.0,No Data,5200000.0
239,Dwight Powell,Dallas Mavericks,7.0,PF,24.0,6-11,240.0,Stanford,845059.0
240,Charlie Villanueva,Dallas Mavericks,3.0,PF,31.0,6-11,232.0,Connecticut,947276.0
251,Dwight Howard,Houston Rockets,12.0,C,30.0,6-11,265.0,No Data,22359364.0
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000.0
298,Tim Duncan,San Antonio Spurs,21.0,C,40.0,6-11,250.0,Wake Forest,5250000.0
316,Mike Muscala,Atlanta Hawks,31.0,PF,24.0,6-11,240.0,Bucknell,947276.0
321,Tiago Splitter,Atlanta Hawks,11.0,C,31.0,6-11,245.0,No Data,9756250.0
339,Chris Bosh,Miami Heat,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730.0
373,Marcin Gortat,Washington Wizards,13.0,C,32.0,6-11,240.0,No Data,11217391.0
375,Nene Hilario,Washington Wizards,42.0,C,33.0,6-11,250.0,No Data,13000000.0
391,Joffrey Lauvergne,Denver Nuggets,77.0,C,24.0,6-11,220.0,No Data,1709719.0
399,Gorgui Dieng,Minnesota Timberwolves,5.0,C,26.0,6-11,241.0,Louisville,1474440.0
400,Kevin Garnett,Minnesota Timberwolves,21.0,PF,40.0,6-11,240.0,No Data,8500000.0
405,Nikola Pekovic,Minnesota Timberwolves,14.0,C,30.0,6-11,307.0,No Data,12100000.0
418,Enes Kanter,Oklahoma City Thunder,11.0,C,24.0,6-11,245.0,Kentucky,16407500.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0

In [30]:
height_groups['Salary'].describe()

        count unique         top freq
Height
5-11      3.0    3.0   1500000.0  1.0
5-9       1.0    1.0   6912869.0  1.0
6-0      10.0    9.0    947276.0  2.0
6-1      16.0   16.0   7000000.0  1.0
6-10     47.0   38.0    947276.0  5.0
6-11     40.0   36.0    845059.0  2.0
6-2      16.0   13.0    947276.0  3.0
6-3      33.0   30.0    947276.0  2.0
6-4      29.0   28.0    947276.0  2.0
6-5      32.0   30.0   8000000.0  2.0
6-6      42.0   37.0    525093.0  4.0
6-7      45.0   41.0    947276.0  4.0
6-8      43.0   37.0    947276.0  4.0
6-9      59.0   48.0    845059.0  5.0
7-0      27.0   24.0   1842000.0  2.0
7-1       7.0    7.0  13000000.0  1.0
7-2       3.0    3.0  15592217.0  1.0
7-3       4.0    4.0   4131720.0  1.0
No Data     1      1     No Data    1

In [13]:
df.Age.value_counts()

24.0       47
25.0       45
27.0       41
23.0       41
26.0       36
28.0       31
30.0       31
29.0       28
22.0       26
31.0       22
20.0       19
21.0       19
33.0       14
32.0       13
34.0       10
36.0       10
35.0        9
37.0        4
38.0        4
40.0        3
39.0        2
19.0        2
No Data     1
Name: Age, dtype: int64

In [26]:
# Convert 'Age' column to numeric
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

bins = [19, 25, 31, 36, 40]
labels = ['19-24', '25-30', '31-35', '36-40']

df['AgeGroup'] = pd.cut(df['Age'], bins=bins, labels=labels, right=False)

In [25]:
display(df['AgeGroup'])

0      25-30
1      25-30
2      25-30
3      19-24
4      25-30
       ...
453    25-30
454    19-24
455    25-30
456    25-30
457      NaN
Name: AgeGroup, Length: 458, dtype: category
Categories (4, object): ['19-24' < '25-30' < '31-35' < '36-40']

In [31]:
df['AgeGroup'].value_counts()

25-30    212
19-24    154
31-35     68
36-40     20
Name: AgeGroup, dtype: int64

In [34]:
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')
df.groupby('AgeGroup')['Salary'].mean()

AgeGroup
19-24    2.706212e+06
25-30    5.895838e+06
31-35    6.662026e+06
36-40    3.847918e+06
Name: Salary, dtype: float64

In [35]:
df.groupby('AgeGroup')['Salary'].median()

AgeGroup
19-24    1654380.0
25-30    4000000.0
31-35    4500000.0
36-40    2814000.0
Name: Salary, dtype: float64

In [37]:
df.groupby('AgeGroup')['Salary'].describe()

,count,mean,std,min,25%,50%,75%,max
AgeGroup,,,,,,,,
19-24,150.0,2.706212e+06,3.188468e+06,30888.0,960457.0,1654380.0,3095650.0,16407501.0
25-30,207.0,5.895838e+06,5.535586e+06,55722.0,1100602.0,4000000.0,9106741.5,22359364.0
31-35,67.0,6.662026e+06,6.281446e+06,200600.0,2092835.5,4500000.0,9697402.5,22970500.0
36-40,19.0,3.847918e+06,5.516191e+06,222888.0,947276.0,2814000.0,3815259.5,25000000.0

In [39]:
List_Of_Categories_In_AgeGroup = list(df['AgeGroup'].value_counts().index)

In [40]:
List_Of_Categories_In_AgeGroup

['25-30', '19-24', '31-35', '36-40']

In [42]:
list_of_salaries = list(df.groupby('AgeGroup')['Salary'])

In [44]:
list_of_salaries = list(df.groupby('AgeGroup')['Salary'])

In [45]:
list_of_salaries

[('19-24',
  3       1148640.0
  6       1170960.0
  8       1824360.0
  9       3431040.0
  10      2569260.0
            ...
  446    12000000.0
  447     1175880.0
  449     1348440.0
  452     2239800.0
  454      900000.0
  Name: Salary, Length: 154, dtype: float64),
 ('25-30',
  0       7730337.0
  1       6796117.0
  2             NaN
  4       5000000.0
  5      12000000.0
            ...
  450     2050000.0
  451      981348.0
  453     2433333.0
  455     2900000.0
  456      947276.0
  Name: Salary, Length: 212, dtype: float64),
 ('31-35',
  19      6300000.0
  31      1635476.0
  33     22875000.0
  34      7402812.0
  43       947276.0
            ...
  375    13000000.0
  394     4345000.0
  413     3750000.0
  415     3135000.0
  434     5016000.0
  Name: Salary, Length: 68, dtype: float64),
 ('36-40',
  46            NaN
  72      2900000.0
  93      5675000.0
  101     3376000.0
  102      947726.0
  109    25000000.0
  119      947276.0
  139     1449187.0
  183     2170465.0
  236     8333334.0
  256      947276.0
  259     5000000.0
  260     3542500.0
  261     4088019.0
  296      947276.0
  299     2814000.0
  343     2854940.0
  392      947276.0
  406      947276.0
  420      222888.0
  Name: Salary, dtype: float64)]



---

##**Dataset - 2: Iris.csv**##

In [14]:
idf = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Datasets/Iris.csv")

In [16]:
idf.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [17]:
idf.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [18]:
idf.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

###**Statistical Details of Iris Species**###

In [19]:
def basic_statistics(df):
    print("\nIris-setosa")
    print(df[df.Species=='Iris-setosa'].describe().transpose())
    print("\nIris-versicolor")
    print(df[df.Species=='Iris-versicolor'].describe().transpose())
    print("\nIris-virginica")
    print(df[df.Species=='Iris-virginica'].describe().transpose())
basic_statistics(idf)

Iris-setosa
               count    mean        std  min     25%   50%     75%   max
Id              50.0  25.500  14.577380  1.0  13.250  25.5  37.750  50.0
SepalLengthCm   50.0   5.006   0.352490  4.3   4.800   5.0   5.200   5.8
SepalWidthCm    50.0   3.418   0.381024  2.3   3.125   3.4   3.675   4.4
PetalLengthCm   50.0   1.464   0.173511  1.0   1.400   1.5   1.575   1.9
PetalWidthCm    50.0   0.244   0.107210  0.1   0.200   0.2   0.300   0.6

Iris-versicolor
               count    mean        std   min     25%    50%    75%    max
Id              50.0  75.500  14.577380  51.0  63.250  75.50  87.75  100.0
SepalLengthCm   50.0   5.936   0.516171   4.9   5.600   5.90   6.30    7.0
SepalWidthCm    50.0   2.770   0.313798   2.0   2.525   2.80   3.00    3.4
PetalLengthCm   50.0   4.260   0.469911   3.0   4.000   4.35   4.60    5.1
PetalWidthCm    50.0   1.326   0.197753   1.0   1.200   1.30   1.50    1.8

Iris-virginica
               count     mean        std    min      25%     50%      75%  \
Id              50.0  125.500  14.577380  101.0  113.250  125.50  137.750
SepalLengthCm   50.0    6.588   0.635880    4.9    6.225    6.50    6.900
SepalWidthCm    50.0    2.974   0.322497    2.2    2.800    3.00    3.175
PetalLengthCm   50.0    5.552   0.551895    4.5    5.100    5.55    5.875
PetalWidthCm    50.0    2.026   0.274650    1.4    1.800    2.00    2.300

                 max
Id             150.0
SepalLengthCm    7.9
SepalWidthCm     3.8
PetalLengthCm    6.9
PetalWidthCm     2.5



---